publicaciones_principales = [
    {
        "id": 1,
        "titulo": "Fundamentos de Estructuras de Datos",
        "autor": "Ana Torres",
        "categoria": "Estructuras de Datos",
        "fecha_publicacion": "2024-05-01",
        "descripcion": "Resumen completo con ejemplos en C++ y Python.",
        "etiquetas": ["listas", "arboles", "pilas", "colas"],
        "imagen_url": "https://www.svgrepo.com/show/508699/landscape-placeholder.svg",
        "publicada": True,
    },
    {
        "id": 2,
        "titulo": "Arquitectura de Computadoras",
        "autor": "Luis Rios",
        "categoria": "Arquitectura",
        "fecha_publicacion": "2024-05-03",
        "descripcion": "Esquemas de CPU, memoria cache y buses.",
        "etiquetas": ["cpu", "memoria", "mips"],
        "imagen_url": "https://www.svgrepo.com/show/508699/landscape-placeholder.svg",
        "publicada": True,
    },
    {
        "id": 3,
        "titulo": "Redes de Computadoras - Guia practica",
        "autor": "Maria Huaman",
        "categoria": "Redes",
        "fecha_publicacion": "2024-04-25",
        "descripcion": "Modelos OSI y TCP/IP con ejemplos de paquetes.",
        "etiquetas": ["tcp", "osi", "protocolos"],
        "imagen_url": "https://www.svgrepo.com/show/508699/landscape-placeholder.svg",
        "publicada": False,
    },
    {
        "id": 4,
        "titulo": "Base de Datos - Apuntes para parciales",
        "autor": "Carlos Vega",
        "categoria": "Base de Datos",
        "fecha_publicacion": "2024-04-28",
        "descripcion": "Modelo relacional, algebra relacional, SQL.",
        "etiquetas": ["sql", "relacional", "joins"],
        "imagen_url": "https://www.svgrepo.com/show/508699/landscape-placeholder.svg",
        "publicada": True,
    },
    {
        "id": 5,
        "titulo": "Desarrollo Web con Flask",
        "autor": "Luis Rios",
        "categoria": "Desarrollo Web",
        "fecha_publicacion": "2024-05-04",
        "descripcion": "Tutorial paso a paso para apps con Python.",
        "etiquetas": ["flask", "python", "web"],
        "imagen_url": "https://www.svgrepo.com/show/508699/landscape-placeholder.svg",
        "publicada": False,
    },
    {
        "id": 6,
        "titulo": "Ingenieria de Requisitos - Ejemplos reales",
        "autor": "Ana Torres",
        "categoria": "Ingenieria de Software",
        "fecha_publicacion": "2024-05-10",
        "descripcion": "Casos de uso, historias de usuario, diagramas.",
        "etiquetas": ["requisitos", "uml", "casos_uso"],
        "imagen_url": "https://www.svgrepo.com/show/508699/landscape-placeholder.svg",
        "publicada": True,
    },
    {
        "id": 7,
        "titulo": "Sistemas Operativos - Planificacion de CPU",
        "autor": "Maria Huaman",
        "categoria": "Sistemas Operativos",
        "fecha_publicacion": "2024-05-11",
        "descripcion": "Algoritmos FCFS, SJF, RR explicados.",
        "etiquetas": ["cpu", "procesos", "planificacion"],
        "imagen_url": "https://www.svgrepo.com/show/508699/landscape-placeholder.svg",
        "publicada": True,
    },
]

publicaciones_secundarias = [
    {
        "id": 8,
        "titulo": "Resumen de Introduccion a la Programacion",
        "autor": "Ana Torres",
        "categoria": "Programacion",
        "fecha_publicacion": "2024-03-21",
        "descripcion": "Variables, condicionales, bucles en C.",
        "etiquetas": ["c", "programacion", "bucles"],
        "imagen_url": "https://www.svgrepo.com/show/508699/landscape-placeholder.svg",
        "publicada": True,
    },
    {
        "id": 9,
        "titulo": "POO en Java - Conceptos Clave",
        "autor": "Luis Rios",
        "categoria": "Programacion",
        "fecha_publicacion": "2024-03-25",
        "descripcion": "Clases, objetos, herencia, interfaces.",
        "etiquetas": ["java", "poo", "herencia"],
        "imagen_url": "https://www.svgrepo.com/show/508699/landscape-placeholder.svg",
        "publicada": True,
    },
    {
        "id": 10,
        "titulo": "Algoritmos de Busqueda y Ordenamiento",
        "autor": "Carlos Vega",
        "categoria": "Estructuras de Datos",
        "fecha_publicacion": "2024-03-30",
        "descripcion": "Bubble sort, quicksort, busqueda binaria.",
        "etiquetas": ["ordenamiento", "busqueda"],
        "imagen_url": "https://www.svgrepo.com/show/508699/landscape-placeholder.svg",
        "publicada": False,
    },
    {
        "id": 11,
        "titulo": "SQL Basico en 2 paginas",
        "autor": "Maria Huaman",
        "categoria": "Base de Datos",
        "fecha_publicacion": "2024-04-01",
        "descripcion": "Selects, joins, agrupaciones rapidas.",
        "etiquetas": ["sql", "select", "join"],
        "imagen_url": "https://www.svgrepo.com/show/508699/landscape-placeholder.svg",
        "publicada": True,
    },
    {
        "id": 12,
        "titulo": "Apuntes de Modelado UML",
        "autor": "Ana Torres",
        "categoria": "Ingenieria de Software",
        "fecha_publicacion": "2024-04-03",
        "descripcion": "Diagrama de clases, secuencia, actividades.",
        "etiquetas": ["uml", "modelado"],
        "imagen_url": "https://www.svgrepo.com/show/508699/landscape-placeholder.svg",
        "publicada": True,
    },
    {
        "id": 13,
        "titulo": "Concurrencia y Deadlocks",
        "autor": "Carlos Vega",
        "categoria": "Sistemas Operativos",
        "fecha_publicacion": "2024-04-06",
        "descripcion": "Condiciones de Coffman, prevencion.",
        "etiquetas": ["deadlock", "concurrencia"],
        "imagen_url": "https://www.svgrepo.com/show/508699/landscape-placeholder.svg",
        "publicada": True,
    },
    {
        "id": 14,
        "titulo": "Notas de Seguridad Informatica",
        "autor": "Luis Rios",
        "categoria": "Seguridad",
        "fecha_publicacion": "2024-04-09",
        "descripcion": "Autenticacion, hash, ataques comunes.",
        "etiquetas": ["seguridad", "hash", "csrf"],
        "imagen_url": "https://www.svgrepo.com/show/508699/landscape-placeholder.svg",
        "publicada": False,
    },
]
